locals {
  private_ips = {
    core = try(opentelekomcloud_compute_instance_v2.core.network[0].fixed_ip_v4, "")
    db   = try(opentelekomcloud_compute_instance_v2.db.network[0].fixed_ip_v4, "")
    lb   = try(opentelekomcloud_compute_instance_v2.lb.network[0].fixed_ip_v4, "")
  }

  floating_ips = {
    core = local.eip_enabled.core && length(opentelekomcloud_networking_floatingip_v2.core) > 0 ? opentelekomcloud_networking_floatingip_v2.core[0].address : ""
    db   = local.eip_enabled.db && length(opentelekomcloud_networking_floatingip_v2.db) > 0 ? opentelekomcloud_networking_floatingip_v2.db[0].address : ""
    lb   = local.eip_enabled.lb && length(opentelekomcloud_networking_floatingip_v2.lb) > 0 ? opentelekomcloud_networking_floatingip_v2.lb[0].address : ""
  }

  public_hosts = {
    core = local.floating_ips.core != "" ? local.floating_ips.core : local.private_ips.core
    db   = local.floating_ips.db != "" ? local.floating_ips.db : local.private_ips.db
    lb   = local.floating_ips.lb != "" ? local.floating_ips.lb : local.private_ips.lb
  }

  inventory = {
    core = {
      host       = local.public_hosts.core
      private_ip = local.private_ips.core
      user       = var.ssh_user
      port       = var.ssh_port
    }
    db = {
      host       = local.public_hosts.db
      private_ip = local.private_ips.db
      user       = var.ssh_user
      port       = var.ssh_port
    }
    lb = {
      host       = local.public_hosts.lb
      private_ip = local.private_ips.lb
      user       = var.ssh_user
      port       = var.ssh_port
    }
  }
}

output "ssh_host" {
  value       = local.public_hosts.core
  description = "Primary SSH host (core)."
}

output "ssh_host_core" {
  value       = local.public_hosts.core
  description = "SSH host for the core node."
}

output "ssh_host_db" {
  value       = local.public_hosts.db
  description = "SSH host for the database node."
}

output "ssh_host_lb" {
  value       = local.public_hosts.lb
  description = "SSH host for the load balancer node."
}

output "ssh_user" {
  value       = var.ssh_user
  description = "SSH username."
}

output "ssh_port" {
  value       = var.ssh_port
  description = "SSH port."
}

output "ssh_private_key_pem" {
  value       = coalesce(local.keypair_private_key, "")
  description = "Sensitive private key PEM when generated by Terraform."
  sensitive   = true
}

output "core_ip" {
  value       = local.private_ips.core
  description = "Private IP for the core node."
}

output "db_ip" {
  value       = local.private_ips.db
  description = "Private IP for the database node."
}

output "lb_ip" {
  value       = local.private_ips.lb
  description = "Private IP for the load balancer node."
}

output "inventory" {
  value       = local.inventory
  description = "Inventory-style map of hosts."
}

output "nat_gateway_id" {
  value       = local.nat_enabled ? opentelekomcloud_nat_gateway_v2.main[0].id : null
  description = "NAT gateway ID when enabled."
}

output "nat_eip" {
  value       = local.nat_enabled ? opentelekomcloud_vpc_eip_v1.nat[0].publicip[0].ip_address : null
  description = "Allocated NAT public IP when enabled."
}
